### PR TITLE
Wrapping up nano 5

### PR DESCRIPTION
**Pull request by marina-mosti**
Nuxt scaffolding nano

### CODE REVIEW

**Review by NataliaTepluhina — APPROVED** [review]
Thank you for the new nano! Suggestion about yarn is up to you, it's just a little complaint from yarn lover. Approved :tada:

**Comment by marina-mosti** [comment]
Added yarn references for fear of @NataliaTepluhina 's rage

**Comment by jlooper** [comment]
Merging, and thinking about a badge. I'm probably going to use the nuxt logo :) Thanks Marina!

**Review by jlooper — COMMENTED** [review]
Merged, will copyedit and add badge. Thank you Marina!!

**Pull request merged**
